"""add expense indexes

Revision ID: 74f2130e6927
Revises: 
Create Date: 2026-04-05 19:29:43.656230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f2130e6927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expenses_created_at', 'expenses', ['created_at'], unique=False)
    op.create_index('idx_expenses_user_created', 'expenses', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_expenses_user_id', 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_user_id', table_name='expenses')
    op.drop_index('idx_expenses_user_created', table_name='expenses')
    op.drop_index('idx_expenses_created_at', table_name='expenses')
    # ### end Alembic commands ###
